[versions]
kotlin = "1.8.20"
ksp = "1.8.20-1.0.10"
coroutines = "1.7.2"
ktor = "2.3.0"
activity = "1.6.1"
appcompat = "1.6.1"
core = "1.9.0"
imageLoading = "1.5.2"
decompose = "2.0.0-compose-experimental-beta-01"
essentyLifecycle = "1.1.0"
kotlinDateTime = "0.4.0"


[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "core" }

image-loading = { module = "io.github.qdsfdhvh:image-loader", version.ref = "imageLoading" }

kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinDateTime" }

ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }

ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-serialization-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }

arkivanov-decompose = { module = "com.arkivanov.decompose:decompose", version.ref = "decompose" }
arkivanov-jetbrains-uiext = { module = "com.arkivanov.decompose:extensions-compose-jetbrains", version.ref = "decompose" }


[plugins]
